import type { EyeColorOption, HairColorOption, SkinToneOption } from "@/types";

export const storycotTheme = {
  clerk: {
    colorPrimary: "#fbbf24",
    colorBackground: "#faf9f6",
    borderRadius: "0.75rem",
  },
  stories: {
    wonder: {
      emoji: "✨",
      accent: "#8b5cf6",
      light: "#f5f3ff",
      tKey: "wonder",
    },
    comfort: {
      emoji: "🌙",
      accent: "#3b82f6",
      light: "#eff6ff",
      tKey: "comfort",
    },
    bravery: {
      emoji: "🦁",
      accent: "#f97316",
      light: "#fff7ed",
      tKey: "bravery",
    },
    kindness: {
      emoji: "💛",
      accent: "#eab308",
      light: "#fefce8",
      tKey: "kindness",
    },
    friendship: {
      emoji: "🤝",
      accent: "#ec4899",
      light: "#fdf2f8",
      tKey: "friendship",
    },
    adventure: {
      emoji: "🗺️",
      accent: "#22c55e",
      light: "#f0fdf4",
      tKey: "adventure",
    },
    patience: {
      emoji: "🌿",
      accent: "#16a34a",
      light: "#f0fdf4",
      tKey: "patience",
    },
    honesty: {
      emoji: "⭐",
      accent: "#6366f1",
      light: "#eef2ff",
      tKey: "honesty",
    },
    gratitude: {
      emoji: "🙏",
      accent: "#f59e0b",
      light: "#fffbeb",
      tKey: "gratitude",
    },
    perseverance: {
      emoji: "💪",
      accent: "#ef4444",
      light: "#fef2f2",
      tKey: "perseverance",
    },
    sharing: {
      emoji: "🎁",
      accent: "#14b8a6",
      light: "#f0fdfa",
      tKey: "sharing",
    },
    "dealing with emotions": {
      emoji: "💭",
      accent: "#a855f7",
      light: "#faf5ff",
      tKey: "dealingWithEmotions",
    },
    "trying new things": {
      emoji: "🌈",
      accent: "#6366f1",
      light: "#eef2ff",
      tKey: "tryingNewThings",
    },
  },
  defaultStory: { emoji: "📖", accent: "#5b4e8a", light: "#f5f3ff" },
  appearance: {
    skin: {
      very_fair: "#f7eadf",
      fair: "#efd7c2",
      light: "#dfb996",
      light_medium: "#c48f63",
      medium: "#a66f47",
      medium_deep: "#7f5336",
      deep: "#5c3825",
      very_deep: "#2f1c15",
    } satisfies Record<SkinToneOption, string>,
    hair: {
      black: "#201714",
      dark_brown: "#3a261d",
      medium_brown: "#65412f",
      light_brown: "#8a6248",
      dark_blonde: "#8c7644",
      blonde: "#d9c071",
      auburn: "#8f4a2a",
      red: "#b5542d",
      grey: "#9ca2af",
      other: "#d7dce5",
    } satisfies Record<HairColorOption, string>,
    eyes: {
      dark_brown: "#3a2819",
      brown: "#6a4324",
      hazel: "#7f6a2f",
      green: "#66824c",
      blue: "#587bb9",
      grey: "#95a0b3",
      mixed: "#c08b66",
      other: "#d7dce5",
    } satisfies Record<EyeColorOption, string>,
  },
} as const;
